Repository EnF-EEEEEE/FrontEnd, pull requests merged in 2025-03, with the labels that each got.

#17 feat: 홈 페이지 청년 장년/ 알림없을시 알림함 퍼블리싱
  package-lock.json
  package.json
  public/images/birds/bluebird_280.svg
  public/images/birds/canary_280.svg
  public/images/birds/crowtit_280.svg
  public/images/birds/home_birds.svg
  public/images/birds/hummingbird_280.svg
  public/images/birds/owl_280.svg
  public/images/birds/parrot_280.svg
  public/images/icons/arrow_left_icon.svg
  public/images/icons/close_icon.svg
  public/images/icons/home_report_icon.svg
  public/images/icons/notification_bell_icon.svg
  public/images/logo/logo_black_M.svg
  src/app/NotificationBox/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Icons/Footer_home_icon.tsx
  src/components/Icons/Footer_letter_icon.tsx
  src/components/Icons/Footer_mybirdy_icon.tsx
  src/components/Icons/Header_bell_icon.tsx
  src/components/Icons/Home_letter_icon.tsx
  src/components/home/Banner.tsx
  src/components/home/HomeMainAdult.tsx
  src/components/home/HomeMainYouth.tsx
  src/components/home/Limit.tsx
  src/components/home/Report.tsx
  tailwind.config.js
Labels: design

#19 feat: 카카오 로그인기능 구현
  birdtest-logic-specification.ts
  next.config.ts
  src/app/(auth)/callback/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/home/page.tsx
  src/app/hooks/useAuth.ts
  src/app/hooks/useLetter.ts
  src/app/hooks/useToast.ts
  src/app/letters/[id]/page.tsx
  src/app/letters/layout.tsx
  src/app/letters/page.tsx
  src/app/page.tsx
  src/components/Botton.tsx
  src/components/Footer.tsx
  src/components/Modal.tsx
  src/components/signup/BuddyTest.tsx
  src/components/signup/CategoryStep.tsx
  src/components/signup/CompleteStep.tsx
  src/components/signup/NicknameStep.tsx
  src/components/signup/RoleStep.tsx
  src/components/signup/TermsStep.tsx
  src/components/ui/Footer.tsx
  src/components/ui/Header.tsx
  src/lib/api.ts
  src/lib/constants.ts
  src/lib/fomatDate.ts
  src/lib/kakaoAuth.ts
  src/lib/validation.ts
  src/services/authService.ts
  src/services/letterService.ts
  src/services/mentorService.ts
  src/store/authStore.ts
  src/store/letterStore.ts
  src/store/queryClient.ts
Labels: feat

#20 feat: 알림함 퍼블리싱, 보관함 진행중, 폰트추가
  public/images/birds/bluebird_40.svg
  public/images/birds/bluebird_tip.svg
  public/images/birds/canary_40.svg
  public/images/birds/canary_tip.svg
  public/images/birds/crowtit_40.svg
  public/images/birds/crowtit_tip.svg
  public/images/birds/hummingbird_40.svg
  public/images/birds/hummingbird_tip.svg
  public/images/birds/letter_storage_bird.svg
  public/images/birds/owl_40.svg
  public/images/birds/owl_tip.svg
  public/images/birds/parrot_40.svg
  public/images/birds/parrot_tip.svg
  public/images/birds/unknownbird_40.svg
  public/images/icons/timer_icon.svg
  src/app/(footershare)/home/page.tsx
  src/app/(footershare)/layout.tsx
  src/app/(footershare)/letter-storage/page.tsx
  src/app/NotificationBox/page.tsx
  src/app/fonts/PretendardVariable.woff2
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/notification-box/page.tsx
  src/components/Icons/Footer_letter_icon.tsx
  src/components/home/Banner.tsx
  src/components/home/HomeMainSenior.tsx
  src/components/home/HomeMainYouth.tsx
  src/components/home/Limit.tsx
  src/components/home/SendMessage.tsx
  src/components/home/SendMessageLimit.tsx
  src/components/notification/SeniorNotificationPage.tsx
  src/components/notification/YouthNotificationPage.tsx
  src/components/ui/Footer.tsx
  src/components/ui/Header.tsx
Labels: design

#22 feat: 보관함 퍼블리싱 및 더미데이터 테스트
  public/images/birds/뱁새_60.svg
  public/images/birds/벌새_60.svg
  public/images/birds/앵무새_60.svg
  public/images/birds/올빼미_60.svg
  public/images/birds/익명새_60.svg
  public/images/birds/카나리아_60.svg
  public/images/birds/파랑새_40.svg
  public/images/birds/파랑새_60.svg
  public/images/icons/bookmark_icon.svg
  public/images/icons/reddot_icon.svg
  src/app/(footershare)/letter-storage/page.tsx
  src/app/letter-detail/page.tsx
  src/app/notification-box/page.tsx
  src/components/Icons/Bookmark_icon.tsx
  src/components/Icons/Header_bell_icon.tsx
  src/components/letter-storage/SeniorLetterStorage.tsx
  src/components/letter-storage/YouthLetterStorage.tsx
  src/components/ui/Footer.tsx
  src/services/homeGetApi.ts
Labels: feat, design

#24 feat: 온보딩 작업 완료
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/images/common/background_main.svg
  public/images/onboarding/step1.svg
  public/images/onboarding/step2.svg
  public/images/onboarding/step3.svg
  public/images/onboarding/step4.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(auth)/login/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/home/layout.tsx
  src/app/home/letter-storage/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/components/Icons/common/LeftArrow.tsx
  src/components/Icons/common/Logo.tsx
  src/components/common/Background.tsx
  src/components/main/MainNav.tsx
  src/components/onboarding/page.tsx
  src/components/signup/BuddyTest.tsx
  src/components/ui/BottomButton.tsx
  src/components/ui/KakaoLogin.tsx
  src/services/authService.ts
  src/store/authStore.ts
  tailwind.config.js
Labels: feat

#30 feat:역할 및 카테고리 선택 단계 구현
  package-lock.json
  package.json
  public/images/animations/bluebird_deliver.json
  public/images/animations/canaria_deliver.json
  public/images/animations/hummingbird_deliver.json
  public/images/animations/loading_egg.json
  public/images/animations/loading_result.json
  public/images/animations/owl_deliver.json
  public/images/animations/parrot_deliver.json
  public/images/animations/parrotbill_deliver.json
  public/images/category/career.svg
  public/images/category/finance.svg
  public/images/category/housing.svg
  public/images/category/life.svg
  public/images/category/love.svg
  public/images/category/mental.svg
  public/images/category/other.svg
  public/images/category/relationship.svg
  public/images/role/mentee.svg
  public/images/role/mentor.svg
  public/images/signup/bluebird-2.svg
  public/images/signup/bluebird-3.svg
  public/images/signup/bluebird.svg
  public/images/terms/arrow-right.svg
  public/images/terms/terms-icon-select_all.svg
  public/images/terms/terms-icon_all.svg
  public/images/terms/terms-icon_check.svg
  public/images/terms/terms-icon_select.svg
  src/app/(auth)/signup/page.tsx
  src/components/common/InfoBox.tsx
  src/components/common/NextButton.tsx
  src/components/signup/BuddyTest.tsx
  src/components/signup/CategoryStep.tsx
  src/components/signup/CompleteStep.tsx
  src/components/signup/NicknameStep.tsx
  src/components/signup/RoleCard.tsx
  src/components/signup/RoleStep.tsx
  src/components/signup/SignupIntro.tsx
  src/components/signup/TermsStep.tsx
Labels: feat

#33 feat:버디 테스트 구현
  public/images/birds/뱁새_280.png
  public/images/birds/벌새_280.png
  public/images/birds/앵무새_280.png
  public/images/birds/올빼미_280.png
  public/images/birds/카나리아_280.png
  public/images/birds/파랑새_280.png
  public/images/buddy-test/intro.png
  public/images/icons/icon_check.svg
  src/app/(auth)/signup/page.tsx
  src/components/signup/BuddyTest.tsx
  src/components/signup/CompleteStep.tsx
  src/components/signup/NicknameStep.tsx
  src/components/signup/SignupIntro.tsx
  src/components/signup/SignupNav.tsx
  src/components/signup/buddytest/BuddyResultCard.tsx
  src/components/signup/buddytest/BuddyTest.tsx
  src/components/signup/buddytest/BuddyTestIntro.tsx
  src/components/signup/buddytest/BuddyTestLoading.tsx
  src/components/signup/buddytest/BuddyTestStep.tsx
  src/constants/birdStyles.ts
  src/constants/buddyTestQuestions.ts
  src/services/buddyService.ts
  src/util/buddyTestUtils.ts
Labels: feat

#36 fix: 배포 에러로 인한 코드 정리
  src/app/(auth)/login/page.tsx
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/components/signup/RoleStep.tsx
  src/components/signup/buddytest/BuddyTestStep.tsx
  src/components/ui/Footer.tsx
  src/constants/menuItems.ts
Labels: fix

#38 fix: 빌드 에러 수정
  src/animations/bluebird_deliver.json
  src/animations/canaria_deliver.json
  src/animations/hummingbird_deliver.json
  src/animations/loading_egg.json
  src/animations/loading_result.json
  src/animations/owl_deliver.json
  src/animations/parrot_deliver.json
  src/animations/parrotbill_deliver.json
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/components/signup/CompleteStep.tsx
  src/components/signup/buddytest/BuddyResultCard.tsx
  src/components/signup/buddytest/BuddyTestLoading.tsx
  src/util/buddyTestUtils.ts
Labels: fix

#39 fix: 배포에러 추가 수정
  src/services/authService.ts
  src/services/userService.ts
Labels: fix

#40 fix: Lottie 파일 기본 import 방식에 따른 배포 에러 수정
  src/components/signup/CompleteStep.tsx
  src/components/signup/buddytest/BuddyTestLoading.tsx
Labels: fix

#59 fix: 추가 병합 완료
  src/components/mybuddy/profileSection.tsx
Labels: fix

#61 fix: utf-8 에러 해결
  public/images/letter-slide/baepsae_profile.png
  public/images/letter-slide/bluebird_profile.png
  public/images/letter-slide/canary_profile.png
  public/images/letter-slide/default_profile.png
  public/images/letter-slide/hummingbird_profile.png
  public/images/letter-slide/owl_profile.png
  public/images/letter-slide/parrot_profile.png
  src/animations/baepsae_deliver.json
  src/animations/bluebird_deliver.json
  src/animations/canary_deliver.json
  src/animations/hummingbird_deliver.json
  src/animations/owl_deliver.json
  src/animations/parrot_deliver.json
  src/app/reply/complete/page.tsx
  src/components/letter/LetterSent.tsx
  src/components/letter/SelectBird.tsx
  src/components/mybuddy/profileSection.tsx
  src/components/signup/buddytest/BuddyImage.tsx
  src/constants/birdNameMap.ts
Labels: fix

#71 fix: 편지작성 - 새 카테고리
  src/app/(footershare)/home/page.tsx
  src/app/(footershare)/layout.tsx
  src/app/(footershare)/mybirdy/page.tsx
  src/app/(main)/layout.tsx
  src/app/layout.tsx
  src/app/onboarding/page.tsx
  src/components/home/Banner.tsx
  src/components/home/HomeMainSenior.tsx
  src/components/home/HomeMainYouth.tsx
  src/components/home/SendMessage.tsx
  src/components/letter/Category.tsx
  src/components/letter/LetterSent.tsx
  src/components/letter/SelectBird.tsx
  src/components/ui/Footer.tsx
  src/components/ui/Header.tsx
  src/constants/birdTraitsStyles.ts
Labels: fix
